/* eslint-disable */

/**
 * Generated by Verge3D Puzzles v.4.11.0
 * Tue, 03 Feb 2026 14:39:44 GMT
 * Prefer not editing this file as your changes may get overridden once Puzzles are saved.
 * Check out https://www.soft8soft.com/docs/manual/en/introduction/Using-JavaScript.html
 * for the information on how to add your own JavaScript to Verge3D apps.
 */
function createPL(v3d = window.v3d) {

// global variables used in the init tab
const _initGlob = {
    percentage: 0,
    output: {
        initOptions: {
            fadeAnnotations: true,
            useBkgTransp: false,
            preserveDrawBuf: false,
            useCompAssets: false,
            useFullscreen: true,
            useCustomPreloader: false,
            preloaderStartCb: function() {},
            preloaderProgressCb: function() {},
            preloaderEndCb: function() {},
        },
    },
};


// global variables/constants used by puzzles' functions
var _pGlob = {};

_pGlob.objCache = new Map();
_pGlob.fadeAnnotations = true;
_pGlob.pickedObject = '';
_pGlob.hoveredObject = '';
_pGlob.mediaElements = {};
_pGlob.loadedFile = '';
_pGlob.states = [];
_pGlob.percentage = 0;
_pGlob.openedFile = '';
_pGlob.openedFileMeta = {};
_pGlob.xrSessionAcquired = false;
_pGlob.xrSessionCallbacks = [];
_pGlob.screenCoords = new v3d.Vector2();
_pGlob.intervalTimers = {};
_pGlob.customEvents = new v3d.EventDispatcher();
_pGlob.eventListeners = [];
_pGlob.htmlElements = new Set();
_pGlob.materialsCache = new Map();
_pGlob.css3Objects = new WeakMap();

_pGlob.AXIS_X = new v3d.Vector3(1, 0, 0);
_pGlob.AXIS_Y = new v3d.Vector3(0, 1, 0);
_pGlob.AXIS_Z = new v3d.Vector3(0, 0, 1);
_pGlob.MIN_DRAG_SCALE = 10e-4;
_pGlob.SET_OBJ_ROT_EPS = 1e-8;

_pGlob.vec2Tmp = new v3d.Vector2();
_pGlob.vec2Tmp2 = new v3d.Vector2();
_pGlob.vec3Tmp = new v3d.Vector3();
_pGlob.vec3Tmp2 = new v3d.Vector3();
_pGlob.vec3Tmp3 = new v3d.Vector3();
_pGlob.vec3Tmp4 = new v3d.Vector3();
_pGlob.eulerTmp = new v3d.Euler();
_pGlob.eulerTmp2 = new v3d.Euler();
_pGlob.quatTmp = new v3d.Quaternion();
_pGlob.quatTmp2 = new v3d.Quaternion();
_pGlob.colorTmp = new v3d.Color();
_pGlob.mat4Tmp = new v3d.Matrix4();
_pGlob.planeTmp = new v3d.Plane();
_pGlob.raycasterTmp = new v3d.Raycaster(); // always check visibility

const createPzLib = ({ v3d=null, appInstance=null }) => {
    function isObjectWorthProcessing(obj) {
        return obj.name !== '' &&
                !(obj.isMesh && obj.isMaterialGeneratedMesh) &&
                !obj.isAuxClippingMesh;
    }
        
    function getObjectByName(objName) {
        let objFound = null;
    
        // COMPAT: <4.9.0, old engine, new puzzles
        const isID = v3d.MathUtils.checkUUID ? v3d.MathUtils.checkUUID(objName) : false;
    
        const pGlobAvailable = _pGlob !== undefined;
        if (pGlobAvailable)
            objFound = _pGlob.objCache.get(objName);
    
        if (objFound && (isID ? objFound.uuid === objName : objFound.name === objName))
            return objFound;
    
        function findValidByName(obj, objName) {
            if ((isID ? obj.uuid === objName : obj.name === objName) && isObjectWorthProcessing(obj))
                return obj;
    
            for (let i = 0; i < obj.children.length; i++) {
                const child = obj.children[i];
                const object = findValidByName(child, objName);
                if (object !== null)
                    return object;
            }
    
            return null;
        }
    
        if (appInstance.scene) {
            objFound = findValidByName(appInstance.scene, objName);
            if (objFound && pGlobAvailable)
                _pGlob.objCache.set(objName, objFound);
        }
    
        return objFound;
    }
        
    function getObjectNamesByGroupName(groupName) {
        const objNameList = [];
        appInstance.scene.traverse(obj => {
            if (isObjectWorthProcessing(obj)) {
                const objGroupNames = obj.groupNames;
                if (!objGroupNames) {
                    return;
                }
    
                for (let i = 0; i < objGroupNames.length; i++) {
                    const objGroupName = objGroupNames[i];
                    if (objGroupName === groupName) {
                        objNameList.push(obj.name);
                    }
                }
            }
        });
        return objNameList;
    }
        
    function getAllObjectNames() {
        const objNameList = [];
        appInstance.scene.traverse(obj => {
            if (isObjectWorthProcessing(obj)) {
                objNameList.push(obj.name);
            }
        });
        return objNameList;
    }
        
    function retrieveObjectNamesAccum(currObjNames, namesAccum) {
        if (typeof currObjNames === 'string') {
            namesAccum.push(currObjNames);
        } else if (Array.isArray(currObjNames) && currObjNames[0] === 'GROUP') {
            const newObjNames = getObjectNamesByGroupName(currObjNames[1]);
            for (let i = 0; i < newObjNames.length; i++) {
                namesAccum.push(newObjNames[i]);
            }
        } else if (Array.isArray(currObjNames) && currObjNames[0] === 'ALL_OBJECTS') {
            const newObjNames = getAllObjectNames();
            for (let i = 0; i < newObjNames.length; i++) {
                namesAccum.push(newObjNames[i]);
            }
        } else if (Array.isArray(currObjNames)) {
            for (let i = 0; i < currObjNames.length; i++) {
                retrieveObjectNamesAccum(currObjNames[i], namesAccum);
            }
        }
    }
        
    function retrieveObjectNames(objNames) {
        const accum = [];
        retrieveObjectNamesAccum(objNames, accum);
        return accum.filter(name => name !== '');
    }
        
    function areListenersSame(target0, type0, listener0, optionsOrUseCapture0,
            target1, type1, listener1, optionsOrUseCapture1) {
        const capture0 = Boolean(optionsOrUseCapture0 instanceof Object
                ? optionsOrUseCapture0.capture : optionsOrUseCapture0);
        const capture1 = Boolean(optionsOrUseCapture1 instanceof Object
                ? optionsOrUseCapture1.capture : optionsOrUseCapture1);
        return target0 === target1 && type0 === type1 && listener0 === listener1
                && capture0 === capture1;
    }
        
    function bindListener(target, type, listener, optionsOrUseCapture) {
        const alreadyExists = _pGlob.eventListeners.some(elem => {
            return areListenersSame(elem.target, elem.type, elem.listener,
                    elem.optionsOrUseCapture, target, type, listener,
                    optionsOrUseCapture);
        });
    
        if (!alreadyExists) {
            target.addEventListener(type, listener, optionsOrUseCapture);
            _pGlob.eventListeners.push({ target, type, listener,
                    optionsOrUseCapture });
        }
    }
        
    function getElement(id, isParent=false) {
        let elem;
        if (Array.isArray(id) && id[0] === 'CONTAINER') {
            if (appInstance !== null) {
                elem = appInstance.container;
            } else if (typeof _initGlob !== 'undefined') {
                // if we are on the initialization stage, we still can have access
                // to the container element
                const contId = _initGlob.container;
                elem = isParent ? parent.document.getElementById(contId)
                        : document.getElementById(contId);
            }
        } else if (Array.isArray(id) && id[0] === 'WINDOW') {
            elem = isParent ? parent : window;
        } else if (Array.isArray(id) && id[0] === 'DOCUMENT') {
            elem = isParent ? parent.document : document;
        } else if (Array.isArray(id) && id[0] === 'BODY') {
            elem = isParent ? parent.document.body : document.body;
        } else if (Array.isArray(id) && id[0] === 'QUERYSELECTOR') {
            elem = isParent ? parent.document.querySelector(id)
                    : document.querySelector(id);
        } else {
            elem = isParent ? parent.document.getElementById(id)
                    : document.getElementById(id);
        }
        return elem;
    }
        
    function getElements(ids, isParent=false) {
        const elems = [];
        if (Array.isArray(ids) && ids[0] !== 'CONTAINER' && ids[0] !== 'WINDOW'
                && ids[0] !== 'DOCUMENT' && ids[0] !== 'BODY'
                && ids[0] !== 'QUERYSELECTOR') {
            for (let i = 0; i < ids.length; i++) {
                elems.push(getElement(ids[i], isParent));
            }
        } else {
            elems.push(getElement(ids, isParent));
        }
        return elems;
    }
        
    function getObjectName(obj) {
        // auto-generated from a multi-material object, use parent name instead
        if (obj.isMesh && obj.isMaterialGeneratedMesh && obj.parent) {
            return obj.parent.name;
        } else {
            return obj.name;
        }
    }
        
    function getObjectUUID(obj) {
        // auto-generated from a multi-material object, use parent UUID instead
        if (obj.isMesh && obj.isMaterialGeneratedMesh && obj.parent) {
            return obj.parent.uuid;
        } else {
            return obj.uuid;
        }
    }
        
    function initObjectPicking(callback, eventType, mouseDownUseTouchStart=false,
            allowedMouseButtons=null) {
    
        // css renderer prevents interacting with canvas, in that case we assign events on container
        const elem = appInstance.cssRenderer ? appInstance.container : appInstance.renderer.domElement;
        bindListener(elem, eventType, pickListener);
    
        if (eventType === 'mousedown') {
    
            const touchEventName = mouseDownUseTouchStart ? 'touchstart' : 'touchend';
            bindListener(elem, touchEventName, pickListener);
    
        } else if (eventType === 'dblclick') {
    
            let prevTapTime = 0;
    
            function doubleTapCallback(event) {
                const now = new Date().getTime();
                const timesince = now - prevTapTime;
    
                if (timesince < 600 && timesince > 0) {
                    pickListener(event);
                    prevTapTime = 0;
                    return;
                }
    
                prevTapTime = new Date().getTime();
            }
    
            const touchEventName = mouseDownUseTouchStart ? 'touchstart' : 'touchend';
            bindListener(elem, touchEventName, doubleTapCallback);
        }
    
        const raycaster = new v3d.Raycaster();
    
        function pickListener(event) {
    
            // to handle unload in loadScene puzzle
            if (!appInstance.getCamera()) {
                return;
            }
    
            event.preventDefault();
    
            let xNorm = 0;
            let yNorm = 0;
            if (event instanceof MouseEvent) {
                if (allowedMouseButtons !== null && allowedMouseButtons.indexOf(event.button) === -1) {
                    return;
                }
                xNorm = event.offsetX / elem.clientWidth;
                yNorm = event.offsetY / elem.clientHeight;
            } else if (event instanceof TouchEvent) {
                const rect = elem.getBoundingClientRect();
                xNorm = (event.changedTouches[0].clientX - rect.left) / rect.width;
                yNorm = (event.changedTouches[0].clientY - rect.top) / rect.height;
            }
    
            _pGlob.screenCoords.x = xNorm * 2 - 1;
            _pGlob.screenCoords.y = -yNorm * 2 + 1;
            raycaster.setFromCamera(_pGlob.screenCoords, appInstance.getCamera(true));
    
            const objList = [];
            appInstance.scene.traverse(obj => objList.push(obj));
    
            const intersects = raycaster.intersectObjects(objList, false);
            callback(intersects, event);
        }
    }
        
    function isObjectAmongObjects(objNameToCheck, objUUIDToCheck, objNames) {
        if (!objNameToCheck) {
            return false;
        }
    
        // COMPAT: <4.10, when calling with 2 arguments
        if (Array.isArray(objUUIDToCheck)) {
            objNames = objUUIDToCheck;
            objUUIDToCheck = objNameToCheck;
        }
    
        for (let i = 0; i < objNames.length; i++) {
            const objName = objNames[i];
    
            // COMPAT: < 4.10 (4.9), old engine, new puzzles
            const isID = v3d.MathUtils.checkUUID ? v3d.MathUtils.checkUUID(objName) : false;
    
            if ((isID ? objUUIDToCheck : objNameToCheck) === objName) {
                return true;
            } else {
                // also check children which are auto-generated for multi-material objects
                const obj = getObjectByName(objName);
                if (obj && obj.type === 'Group') {
                    for (let j = 0; j < obj.children.length; j++) {
                        // if parent referred by UUID, compare children also by UUID
                        if (isID ? (objUUIDToCheck === obj.children[j].uuid) : (objNameToCheck === obj.children[j].name)) {
                            return true;
                        }
                    }
                }
            }
        }
        return false;
    }

    return {
        getObjectByName, retrieveObjectNames, bindListener, getElements,
        getObjectName, getObjectUUID, initObjectPicking, isObjectAmongObjects,
    };
};

var PL = {};



// backward compatibility
if (v3d[Symbol.toStringTag] !== 'Module') {
    v3d.PL = v3d.puzzles = PL;
}

PL.procedures = PL.procedures || {};




PL.execInitPuzzles = function(options) {
    // always null, should not be available in "init" puzzles
    var appInstance = null;
    // app is more conventional than appInstance (used in exec script and app templates)
    var app = null;

    const PzLib = createPzLib({ v3d });

    // provide the container's id to puzzles that need access to the container
    _initGlob.container = options !== undefined && 'container' in options
            ? options.container : "";

    

    
    return _initGlob.output;
}

PL.init = function(appInstance, initOptions) {

// app is more conventional than appInstance (used in exec script and app templates)
var app = appInstance;

const PzLib = createPzLib({ v3d, appInstance });

initOptions = initOptions || {};

if ('fadeAnnotations' in initOptions) {
    _pGlob.fadeAnnotations = initOptions.fadeAnnotations;
}



var Doble_boca_activada;

// show and hide puzzles
function changeVis(objSelector, bool) {
    var objNames = PzLib.retrieveObjectNames(objSelector);

    for (var i = 0; i < objNames.length; i++) {
        var objName = objNames[i]
        if (!objName)
            continue;
        var obj = PzLib.getObjectByName(objName);
        if (!obj)
            continue;
        obj.visible = bool;
        obj.resolveMultiMaterial().forEach(function(objR) {
            objR.visible = bool;
        });
    }
}

// eventHTMLElem puzzle
function eventHTMLElem(eventType, ids, isParent, callback) {
    var elems = PzLib.getElements(ids, isParent);
    for (var i = 0; i < elems.length; i++) {
        var elem = elems[i];
        if (!elem)
            continue;

        PzLib.bindListener(elem, eventType, callback);
    }
}

// isObjectVisible puzzle
function isObjectVisible(objSelector) {
    var objNames = PzLib.retrieveObjectNames(objSelector);

    for (var i = 0; i < objNames.length; i++) {
        var objName = objNames[i]
        if (!objName)
            continue;
        var obj = PzLib.getObjectByName(objName);
        if (!obj)
            continue;
        if (obj.visible)
            return true;
    }
    return false;
}

// whenClicked puzzle
function registerOnClick(objSelector, xRay, doubleClick, mouseButtons, useID, cbDo, cbIfMissedDo) {

    // for AR/VR
    _pGlob.objClickInfo = _pGlob.objClickInfo || [];

    _pGlob.objClickInfo.push({
        objSelector: objSelector,
        useID: useID,
        callbacks: [cbDo, cbIfMissedDo]
    });

    PzLib.initObjectPicking(function(intersects, event) {

        let isPicked = false;

        const maxIntersects = xRay ? intersects.length : Math.min(1, intersects.length);

        for (let i = 0; i < maxIntersects; i++) {
            const obj = intersects[i].object;

            const objName = PzLib.getObjectName(obj);
            const objUUID = PzLib.getObjectUUID(obj);
            const objNames = PzLib.retrieveObjectNames(objSelector);

            if (PzLib.isObjectAmongObjects(objName, objUUID, objNames)) {
                // save the object for the pickedObject block
                _pGlob.pickedObject = useID ? objUUID : objName;
                isPicked = true;
                cbDo(event);
            }
        }

        if (!isPicked) {
            _pGlob.pickedObject = '';
            cbIfMissedDo(event);
        }

    }, doubleClick ? 'dblclick' : 'mousedown', false, mouseButtons);
}

// assignMaterial puzzle
function assignMat(objSelector, matName, matIndex) {
    const objNames = PzLib.retrieveObjectNames(objSelector);
    if (!matName)
        return;

    const isMaterialInScene = (mat) => v3d.SceneUtils.getMaterialsByName(appInstance, mat.name).some(iMat => iMat === mat);
    const materialsCache = _pGlob.materialsCache;
    const mat = materialsCache.get(matName) || v3d.SceneUtils.getMaterialByName(appInstance, matName);
    if (!mat)
        return;
    for (let i = 0; i < objNames.length; i++) {
        const objName = objNames[i];
        if (!objName)
            continue;
        const obj = PzLib.getObjectByName(objName);
        if (obj) {
            const objsM = obj.resolveMultiMaterial();

            let objM;
            if (Number.isInteger(matIndex)) {
                if (matIndex >= 1 && matIndex <= objsM.length) {
                    objM = objsM[matIndex-1];
                } else {
                    console.error('assign material puzzle: Invalid material index ' + matIndex);
                    continue;
                }
            } else {
                objM = objsM[0];
            }

            const oldMat = objM.material;
            if (!oldMat)
                continue; // pass silently

            objM.material = mat;

            if (!isMaterialInScene(oldMat)) {
                materialsCache.set(oldMat.name, oldMat);
            }
        }
    }

    if (materialsCache.has(mat.name) && isMaterialInScene(mat)) {
        materialsCache.delete(mat.name);
    }
}

// getObjectMaterial puzzle
function getObjectMaterial(objSelector, matIndex, useID) {
    const objNames = PzLib.retrieveObjectNames(objSelector);

    for (let i = 0; i < objNames.length; i++) {
        const objName = objNames[i]
        if (!objName)
            continue;
        let obj = PzLib.getObjectByName(objName);
        if (!obj)
            continue;

        const objsM = obj.resolveMultiMaterial();

        if (Number.isInteger(matIndex)) {
            if (matIndex >= 1 && matIndex <= objsM.length) {
                obj = objsM[matIndex-1];
            } else {
                console.error('get object material puzzle: invalid material index ' + matIndex);
                continue;
            }
        } else {
            obj = objsM[0];
        }

        if (obj.material) {
            // COMPAT: <4.9.0, old engine, new puzzles, see getMaterialByName()
            if (useID && v3d.MathUtils.checkUUID)
                return obj.material.uuid;
            else
                return obj.material.name;
        } else {
            console.error('get object material puzzle: invalid object ' + obj.name);
        }
    }
    return '';
}


eventHTMLElem('click', 'PLANTILLA TIPO DE BOCA', false, function(event) {
    changeVis(['ALL_OBJECTS'], false);
    changeVis('Suelo sin fondo', true);
    changeVis('Luz frente', true);
    changeVis('Luz trasera', true);
    changeVis('F90', true);
    changeVis('Cuba 3m', true);
    changeVis('Puertas inferiores', true);
    changeVis('<none>', true);
    changeVis('<none>', true);
});
if (Doble_boca_activada == true) {
    changeVis('Cuba 3m', false);
    changeVis('Cuba 3m doble boca', true);
    changeVis('<none>', true);
}

eventHTMLElem('click', 'calibrada', false, function(event) {
    changeVis(['ALL_OBJECTS'], false);
    changeVis('Suelo sin fondo', true);
    changeVis('Luz frente', true);
    changeVis('Luz trasera', true);
    changeVis('F90', true);
    changeVis('Cuba 3m', true);
    changeVis('Puertas inferiores', true);
    changeVis('Papel 3m lado1', true);
    changeVis('Tapa Bocas lado1', true);
    if (Doble_boca_activada == true) {
        changeVis('Cuba 3m', false);
        changeVis('Cuba 3m doble boca', true);
        changeVis('Papel 3m lado2', true);
        changeVis('Tapa Bocas lado2', true);
    }
});

eventHTMLElem('click', 'oscilante', false, function(event) {
    changeVis(['ALL_OBJECTS'], false);
    changeVis('Suelo sin fondo', true);
    changeVis('Luz frente', true);
    changeVis('Luz trasera', true);
    changeVis('F90', true);
    changeVis('Cuba 3m', true);
    changeVis('Puertas inferiores', true);
    changeVis('Oscilante', true);
    changeVis('Tapa Bocas lado1', true);
    if (Doble_boca_activada == true) {
        changeVis('Cuba 3m', false);
        changeVis('Cuba 3m doble boca', true);
        changeVis('Oscilante2', true);
        changeVis('Tapa Bocas lado2', true);
    }
});

eventHTMLElem('click', 'abatible', false, function(event) {
    changeVis(['ALL_OBJECTS'], false);
    changeVis('Suelo sin fondo', true);
    changeVis('Luz frente', true);
    changeVis('Luz trasera', true);
    changeVis('F90', true);
    changeVis('Cuba 3m', true);
    changeVis('Puertas inferiores', true);
    changeVis('Abatible1', true);
    changeVis('Tapa Bocas lado1', true);
    if (Doble_boca_activada == true) {
        changeVis('Cuba 3m', false);
        changeVis('Cuba 3m doble boca', true);
        changeVis('Abatible2', true);
        changeVis('Tapa Bocas lado2', true);
    }
});

eventHTMLElem('click', 'tridimensional', false, function(event) {
    changeVis(['ALL_OBJECTS'], false);
    changeVis('Suelo sin fondo', true);
    changeVis('Luz frente', true);
    changeVis('Luz trasera', true);
    changeVis('F90', true);
    changeVis('Cuba 3m', true);
    changeVis('Puertas inferiores', true);
    changeVis('Abatible1', true);
    changeVis('Tridimensional1', true);
    changeVis('Tapa Bocas lado1', true);
    if (Doble_boca_activada == true) {
        changeVis('Cuba 3m', false);
        changeVis('Cuba 3m doble boca', true);
        changeVis('Abatible2', true);
        changeVis('Tridimensional2', true);
        changeVis('Tapa Bocas lado2', true);
    }
});

changeVis('Scene', false);
registerOnClick('Puertas inferiores', false, false, [0,1,2], false, function(event) {
    if (isObjectVisible('Scene')) {
        changeVis('Scene', false);
    } else {
        changeVis('Scene', true);
    }
}, function(event) {});

eventHTMLElem('click', 'gris7005', false, function(event) {
    assignMat('Cuba 3m', 'Gris7005', undefined);
    assignMat('Cuba 3m doble boca', 'Gris7005', undefined);
    assignMat('Oscilante', getObjectMaterial('Cuba 3m', undefined, false), undefined);
    assignMat('Oscilante2', getObjectMaterial('Cuba 3m', undefined, false), undefined);
});
eventHTMLElem('click', 'gris7035', false, function(event) {
    assignMat('Cuba 3m', 'Gris7035', undefined);
    assignMat('Cuba 3m doble boca', 'Gris7035', undefined);
    assignMat('Oscilante', getObjectMaterial('Cuba 3m', undefined, false), undefined);
    assignMat('Oscilante2', getObjectMaterial('Cuba 3m', undefined, false), undefined);
});
eventHTMLElem('click', 'gris7037', false, function(event) {
    assignMat('Cuba 3m', 'Gris7037', undefined);
    assignMat('Cuba 3m doble boca', 'Gris7037', undefined);
    assignMat('Oscilante', getObjectMaterial('Cuba 3m', undefined, false), undefined);
    assignMat('Oscilante2', getObjectMaterial('Cuba 3m', undefined, false), undefined);
});
eventHTMLElem('click', 'gris7040', false, function(event) {
    assignMat('Cuba 3m', 'Gris7040', undefined);
    assignMat('Cuba 3m doble boca', 'Gris7040', undefined);
    assignMat('Oscilante', getObjectMaterial('Cuba 3m', undefined, false), undefined);
    assignMat('Oscilante2', getObjectMaterial('Cuba 3m', undefined, false), undefined);
});
eventHTMLElem('click', 'azul5002', false, function(event) {
    assignMat('Cuba 3m', 'Azul5002', undefined);
    assignMat('Cuba 3m doble boca', 'Azul5002', undefined);
    assignMat('Oscilante', getObjectMaterial('Cuba 3m', undefined, false), undefined);
    assignMat('Oscilante2', getObjectMaterial('Cuba 3m', undefined, false), undefined);
});
eventHTMLElem('click', 'amarillo1018', false, function(event) {
    assignMat('Cuba 3m', 'Amarillo1018', undefined);
    assignMat('Cuba 3m doble boca', 'Amarillo1018', undefined);
    assignMat('Envase 3m lado1', 'Amarillo1018', undefined);
    assignMat('Envase 3m lado2', 'Amarillo1018', undefined);
    assignMat('Oscilante', getObjectMaterial('Cuba 3m', undefined, false), undefined);
    assignMat('Oscilante2', getObjectMaterial('Cuba 3m', undefined, false), undefined);
});
eventHTMLElem('click', 'amarillo1021', false, function(event) {
    assignMat('Cuba 3m', 'Amarillo1021', undefined);
    assignMat('Cuba 3m doble boca', 'Amarillo1021', undefined);
    assignMat('Envase 3m lado1', 'Amarillo1021', undefined);
    assignMat('Envase 3m lado2', 'Amarillo1021', undefined);
    assignMat('Oscilante', getObjectMaterial('Cuba 3m', undefined, false), undefined);
    assignMat('Oscilante2', getObjectMaterial('Cuba 3m', undefined, false), undefined);
});
eventHTMLElem('click', 'verde6005', false, function(event) {
    assignMat('Cuba 3m', 'Verde6005', undefined);
    assignMat('Cuba 3m doble boca', 'Verde6005', undefined);
    assignMat('Vidrio 3m lado1', 'Verde6005', undefined);
    assignMat('Vidrio 3m lado2', 'Verde6005', undefined);
    assignMat('Oscilante', getObjectMaterial('Cuba 3m', undefined, false), undefined);
    assignMat('Oscilante2', getObjectMaterial('Cuba 3m', undefined, false), undefined);
});
eventHTMLElem('click', 'verde6018', false, function(event) {
    assignMat('Cuba 3m', 'Verde6018', undefined);
    assignMat('Cuba 3m doble boca', 'Verde6018', undefined);
    assignMat('Vidrio 3m lado1', 'Verde6018', undefined);
    assignMat('Vidrio 3m lado2', 'Verde6018', undefined);
    assignMat('Oscilante', getObjectMaterial('Cuba 3m', undefined, false), undefined);
    assignMat('Oscilante2', getObjectMaterial('Cuba 3m', undefined, false), undefined);
});
eventHTMLElem('click', 'verde6032', false, function(event) {
    assignMat('Cuba 3m', 'Verde6032', undefined);
    assignMat('Cuba 3m doble boca', 'Verde6032', undefined);
    assignMat('Vidrio 3m lado1', 'Verde6032', undefined);
    assignMat('Vidrio 3m lado2', 'Verde6032', undefined);
    assignMat('Oscilante', getObjectMaterial('Cuba 3m', undefined, false), undefined);
    assignMat('Oscilante2', getObjectMaterial('Cuba 3m', undefined, false), undefined);
});
eventHTMLElem('click', 'marron8011', false, function(event) {
    assignMat('Cuba 3m', 'Marron8011', undefined);
    assignMat('Cuba 3m doble boca', 'Marron8011', undefined);
    assignMat('Envase 3m lado1', 'Marron8011', undefined);
    assignMat('Envase 3m lado2', 'Marron8011', undefined);
    assignMat('Oscilante', getObjectMaterial('Cuba 3m', undefined, false), undefined);
    assignMat('Oscilante2', getObjectMaterial('Cuba 3m', undefined, false), undefined);
});
eventHTMLElem('click', 'marron8024', false, function(event) {
    assignMat('Cuba 3m', 'Marron8024', undefined);
    assignMat('Cuba 3m doble boca', 'Marron8024', undefined);
    assignMat('Envase 3m lado1', 'Marron8024', undefined);
    assignMat('Envase 3m lado2', 'Marron8024', undefined);
    assignMat('Oscilante', getObjectMaterial('Cuba 3m', undefined, false), undefined);
    assignMat('Oscilante2', getObjectMaterial('Cuba 3m', undefined, false), undefined);
});
eventHTMLElem('click', 'personalizado', false, function(event) {
    assignMat('Cuba 3m', 'BSDF', undefined);
    assignMat('Cuba 3m doble boca', 'BSDF', undefined);
    assignMat('Oscilante', getObjectMaterial('Cuba 3m', undefined, false), undefined);
    assignMat('Oscilante2', getObjectMaterial('Cuba 3m', undefined, false), undefined);
});

eventHTMLElem('click', 'tambor', false, function(event) {
    changeVis(['ALL_OBJECTS'], false);
    changeVis('Suelo sin fondo', true);
    changeVis('Luz frente', true);
    changeVis('Luz trasera', true);
    changeVis('F90', true);
    changeVis('Cuba 3m', true);
    changeVis('Puertas inferiores', true);
    changeVis('cilindro1', true);
    if (Doble_boca_activada == true) {
        changeVis('Cuba 3m', false);
        changeVis('Cuba 3m doble boca', true);
        changeVis('cilindro2', true);
    }
});

eventHTMLElem('click', 'duo', false, function(event) {
    changeVis(['ALL_OBJECTS'], false);
    changeVis('Suelo sin fondo', true);
    changeVis('Luz frente', true);
    changeVis('Luz trasera', true);
    changeVis('F90', true);
    changeVis('Cuba 3m', true);
    changeVis('Puertas inferiores', true);
    changeVis('cilindro1', true);
    if (Doble_boca_activada == true) {
        changeVis('Cuba 3m', false);
        changeVis('Cuba 3m doble boca', true);
        changeVis('cilindro2', true);
    }
});

eventHTMLElem('click', 'papel', false, function(event) {
    changeVis('Papel 3m lado1', true);
    changeVis('Envase 3m lado1', false);
    changeVis('Vidrio 3m lado1', false);
    if (Doble_boca_activada == true) {
        changeVis('Papel 3m lado2', true);
        changeVis('Envase 3m lado2', false);
        changeVis('Vidrio 3m lado2', false);
    }
});

eventHTMLElem('click', 'envases', false, function(event) {
    changeVis('Envase 3m lado1', true);
    changeVis('Papel 3m lado1', false);
    changeVis('Vidrio 3m lado1', false);
    assignMat('Envase 3m lado1', 'Amarillo1021', undefined);
    if (Doble_boca_activada == true) {
        changeVis('Envase 3m lado2', true);
        changeVis('Papel 3m lado2', false);
        changeVis('Vidrio 3m lado2', false);
        assignMat('Envase 3m lado2', 'Amarillo1021', undefined);
    }
});

eventHTMLElem('click', 'vidrio', false, function(event) {
    changeVis('Vidrio 3m lado1', true);
    changeVis('Papel 3m lado1', false);
    changeVis('Envase 3m lado1', false);
    if (Doble_boca_activada == true) {
        changeVis('Vidrio 3m lado2', true);
        changeVis('Papel 3m lado2', false);
        changeVis('Envase 3m lado2', false);
    }
});

eventHTMLElem('click', 'organico', false, function(event) {
    changeVis('Envase 3m lado1', true);
    changeVis('Papel 3m lado1', false);
    changeVis('Vidrio 3m lado1', false);
    assignMat('Envase 3m lado1', 'Marron8024', undefined);
    if (Doble_boca_activada == true) {
        changeVis('Envase 3m lado2', true);
        changeVis('Papel 3m lado2', false);
        changeVis('Vidrio 3m lado2', false);
        assignMat('Envase 3m lado2', 'Marron8024', undefined);
    }
});

eventHTMLElem('click', 'F90', false, function(event) {
    changeVis('F90', true);
    changeVis('Doble gancho', false);
    changeVis('Kinshofer', false);
});

eventHTMLElem('click', 'dobleGancho', false, function(event) {
    changeVis('Doble gancho', true);
    changeVis('F90', false);
    changeVis('Kinshofer', false);
});

eventHTMLElem('click', 'kinshofer', false, function(event) {
    changeVis('Kinshofer', true);
    changeVis('F90', false);
    changeVis('Doble gancho', false);
});

assignMat('Oscilante', getObjectMaterial('Cuba 3m', undefined, false), undefined);
assignMat('Oscilante2', getObjectMaterial('Cuba 3m', undefined, false), undefined);

eventHTMLElem('click', 'dobleBocaNo', false, function(event) {
    changeVis('Cuba 3m', true);
    changeVis('Cuba 3m doble boca', false);
    changeVis('Tapa Bocas lado2', false);
    changeVis('Pedal2', false);
    changeVis('Maneta2', false);
    Doble_boca_activada = false;
    changeVis('Papel 3m lado2', false);
    changeVis('Envase 3m lado2', false);
    changeVis('Vidrio 3m lado2', false);
    changeVis('Oscilante2', false);
    changeVis('Abatible2', false);
    changeVis('Tridimensional2', false);
    changeVis('cilindro2', false);
});

eventHTMLElem('click', 'dobleBocaSi', false, function(event) {
    changeVis('Cuba 3m doble boca', true);
    changeVis('Cuba 3m', false);
    Doble_boca_activada = true;
    if (isObjectVisible('Papel 3m lado1')) {
        changeVis('Papel 3m lado2', true);
        changeVis('Tapa Bocas lado2', true);
    }
    if (isObjectVisible('Envase 3m lado1')) {
        changeVis('Envase 3m lado2', true);
        assignMat('Envase 3m lado2', getObjectMaterial('Envase 3m lado1', undefined, false), undefined);
        changeVis('Tapa Bocas lado2', true);
    }
    if (isObjectVisible('Vidrio 3m lado1')) {
        changeVis('Vidrio 3m lado2', true);
        changeVis('Tapa Bocas lado2', true);
    }
    if (isObjectVisible('Oscilante')) {
        changeVis('Oscilante2', true);
        changeVis('Tapa Bocas lado2', true);
    }
    if (isObjectVisible('Abatible1')) {
        changeVis('Abatible2', true);
        changeVis('Tapa Bocas lado2', true);
    }
    if (isObjectVisible('Tridimensional1')) {
        changeVis('Abatible2', true);
        changeVis('Tridimensional2', true);
    }
    if (isObjectVisible('cilindro1')) {
        changeVis('cilindro2', true);
    }
    if (isObjectVisible('<none>')) {
        changeVis('<none>', true);
    }
});

eventHTMLElem('click', 'pedalNo', false, function(event) {
    changeVis('Pedal1', false);
    changeVis('Pedal2', false);
});
eventHTMLElem('click', 'pedal1', false, function(event) {
    changeVis('Pedal1', true);
    changeVis('Pedal2', false);
});
eventHTMLElem('click', 'pedal2', false, function(event) {
    changeVis('Pedal1', false);
    changeVis('Pedal2', true);
});
eventHTMLElem('click', 'pedal3', false, function(event) {
    changeVis('Pedal1', true);
    changeVis('Pedal2', true);
});

eventHTMLElem('click', 'manetaNo', false, function(event) {
    changeVis('Maneta1', false);
    changeVis('Maneta2', false);
});
eventHTMLElem('click', 'maneta1', false, function(event) {
    changeVis('Maneta1', true);
    changeVis('Maneta2', false);
});
eventHTMLElem('click', 'maneta2', false, function(event) {
    changeVis('Maneta2', true);
    changeVis('Maneta1', false);
});
eventHTMLElem('click', 'maneta3', false, function(event) {
    changeVis('Maneta1', true);
    changeVis('Maneta2', true);
});

eventHTMLElem('click', 'cerradura1', false, function(event) {
    changeVis('<none>', false);
    changeVis('<none>', false);
    changeVis('<none>', false);
    changeVis('<none>', false);
    changeVis('<none>', true);
});



} // end of PL.init function

PL.disposeListeners = function() {
    if (_pGlob) {
        _pGlob.eventListeners.forEach(({ target, type, listener, optionsOrUseCapture }) => {
            target.removeEventListener(type, listener, optionsOrUseCapture);
        });
        _pGlob.eventListeners.length = 0;
    }
}

PL.disposeHTMLElements = function() {
    if (_pGlob) {
        _pGlob.htmlElements.forEach(elem => {
            elem.remove();
        });
        _pGlob.htmlElements.clear();
    }
}

PL.disposeMaterialsCache = function() {
    if (_pGlob) {
        for (const mat of _pGlob.materialsCache.values()) {
            mat.dispose();
        }
        _pGlob.materialsCache.clear();
    }
}

PL.dispose = function() {
    PL.disposeListeners();
    PL.disposeHTMLElements();
    PL.disposeMaterialsCache();
    _pGlob = null;
    // backward compatibility
    if (v3d[Symbol.toStringTag] !== 'Module') {
        delete v3d.PL;
        delete v3d.puzzles;
    }
}



return PL;

}

export { createPL };
